[package]
authors = ['Joystream contributors']
build = 'build.rs'
edition = '2018'
name = 'chain-spec-builder'
version = '3.1.1'

[dependencies]
ansi_term = "0.12.1"
rand = "0.7.3"
structopt = "0.3.8"
sc-keystore = { git = 'https://github.com/paritytech/substrate.git', branch = "rococo-v1", version = '3.0.0' }
sc-telemetry = { git = 'https://github.com/paritytech/substrate.git', branch = "rococo-v1", version = '3.0.0' }
sc-chain-spec = { git = 'https://github.com/paritytech/substrate.git', branch = "rococo-v1", version = '3.0.0' }
sp-core = { git = 'https://github.com/paritytech/substrate.git', branch = "rococo-v1", version = '3.0.0' }
sp-keystore = { git = 'https://github.com/paritytech/substrate.git', branch = "rococo-v1", version = '0.9.0' }
joystream-node = { path = "../../node" }

enum-utils = "0.1.2"
async-std = "1.9.0"
futures-util = "0.3.15"